# Generated by Django 5.2.6 on 2025-10-17 07:41

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nameh", "0004_chatgroup_admin_chatgroup_groupchat_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                max_length=128,
                unique=True,
            ),
        ),
    ]
