# Generated by Django 5.2.6 on 2025-10-19 19:16

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nameh", "0005_groupmessage_file_alter_chatgroup_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                max_length=128,
                unique=True,
            ),
        ),
    ]
